### PR TITLE
build system fixes

### PR DESCRIPTION
**Pull request by martinpitt**
@zonque: Once this lands, could you tag a release, so that we can package this? Now that it got dropped from 230 it's rather urgent. Thanks!

### CODE REVIEW

**Comment by sofar** [comment]
I'll be happy to do a tagged release this week. I'll have to contemplate a numbering scheme before we do, though ;)

**Comment by martinpitt** [comment]
I noticed that the dist tarballs (and neither the upstream source) are missing licenses, added now in a followup commit.

**Comment by martinpitt** [comment]
@sofar, I'd appreciate if you could review this, it should be fairly straightforward.

**Comment by sofar** [comment]
I was about to merge this already.

Merged.

87ed5fafa89e5a352c5fb0e5e75b66ffb6f7121c .. dcb246b46239259ec99b3c6e6ab7d27e1a5a8a84

**Comment by martinpitt** [comment]
nice, thanks!

**Pull request closed without merging**
