### PR TITLE
Increase max pid cpu

### PR DESCRIPTION
**Pull request by alfonsosanchezbeato**
Increase max PID and CPU constants, as the numbers were insufficient for modern servers.

### CODE REVIEW

**Comment by Ablu** [comment]
Any chance to get this merged? :-)

**Comment by mbiebl** [comment]
@ahkok ^ could you have a look at this
There is also this downstream bug report https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=976922

**Comment by ahkok** [comment]
Thanks for the ping, I had completely missed taking care a bit here. Yeah, this makes sense - I'll try and roll this in quickly.

**Comment by ahkok** [comment]
`v234` is out.

**Pull request merged**
