### PR TITLE
fix PSS graph on recent kernels

### LINKED ISSUE #46: Entropy and memory graph heights explode
Something is not quite right with this graph:
[bootchart-20210221-1726.svg.gz](https://github.com/systemd/systemd-bootchart/files/6018139/bootchart-20210221-1726.svg.gz)

Had no luck getting a sane result.. with systemd-bootchart 233-2 in a debian VM and

```
PlotMemoryUsage=yes
PlotEntropyGraph=yes
```

### PR DESCRIPTION
**Pull request by amurzeau**
It seems the smaps file layout in /proc changed in some kernel version. This commit fix it by:
- Using smaps_rollup instead of smaps to avoid having to loop over all entries (smaps_rollup being a summary of smaps)
- Searching "Pss:" instead of using hardcoded offsets (which will probably go wrong again in the future).

Fixes: #46

Note that the issue mentions the entropy graph too, but this one is working fine, only the PSS graph was corrupted (because of random value, some of them negative).

### CODE REVIEW

**Comment by bluca** [comment]
Is this change compatible with both old and new kernels?

**Comment by amurzeau** [comment]
The "Pss:" term exists since the PSS implementation (2.6.25, https://github.com/torvalds/linux/commit/ec4dd3eb35759f9fbeb5c1abb01403b2fde64cc9), but the use of `smaps_rollup` requires a 4.14 kernel.
`smaps_rollup` was introduced here: https://github.com/torvalds/linux/commit/493b0e9d945fa9dfe96be93ae41b4ca4b6fdb317

To avoid the requirement of the 4.14 kernel, the PR needs to be changed to use `smaps` instead and compute the sum of `Pss:` for all occurrences.

**Comment by bluca** [comment]
Why not just check if the smaps_rollup file exists, and if so use the new implementation, and if not fallback to the previous one?

**Comment by amurzeau** [comment]
The previous way was assuming a fixed number of byte for each block in smaps.
There is no real reason except code it was easier to do like this, but this check can be implemented for sure.

**Comment by amurzeau** [comment]
I've introduced the check for the presence of `smaps_rollup`.
I've also replaced `continue` case of failure to open `smaps` with `goto catch_rename` to not skip remaining sampling operations.

**Review by bluca — APPROVED** [review]

**Pull request merged**
